# Generated by Django 5.1.7 on 2025-04-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_rename_addschedule_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.IntegerField(),
        ),
    ]
