# Generated by Django 5.1.7 on 2025-04-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_schedule_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
    ]
