# Generated by Django 5.1.7 on 2025-04-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_remove_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.CharField(max_length=255),
        ),
    ]
