# Generated by Django 5.1.7 on 2025-04-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hour',
            old_name='hour_list',
            new_name='name',
        ),
    ]
