# Generated by Django 5.1.7 on 2025-04-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_rename_hour_list_hour_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hour',
            options={'verbose_name_plural': 'Hours'},
        ),
    ]
