# Generated by Django 5.1.7 on 2025-04-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_alter_hour_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hour',
            options={},
        ),
        migrations.RenameField(
            model_name='hour',
            old_name='name',
            new_name='hour_list',
        ),
    ]
