# Generated by Django 5.1.7 on 2025-04-08 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_alter_hour_options_rename_name_hour_hour_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hour',
            options={'ordering': ('hour_list',)},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.hour'),
        ),
    ]
